### ISSUE TITLE
some problem with comile

### ISSUE THREAD

**Issue by aviran86** [juliourena/plaintext#1]
Hey
i get this msg alert 

......\v4.0.30319\csc.exe uac_bypass_computerdefaults.cs
Microsoft (R) Visual C# Compiler version 4.7.3056.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

how i compile it without upgrade the C# version ?

**Comment by juliourena** [comment]
Which Windows version are you using? Take a look if this is just a notification message and you already got the program compile.
